version: '3'
services:
  database:
    image: postgres:14
    environment:
      POSTGRES_DB: habitbase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      -  postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  postgres:   