spring:
  application:
    name: HabitManager
  datasource:
    url: jdbc:postgresql://${PG_HOST}:5432/${PG_HOST}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
  liquibase:
    change-log: db/changelog/changelog.xml
    enabled: true